# Generated by Django 5.2 on 2025-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='needed_skill_text',
            field=models.TextField(blank=True, help_text='Describe the skills or roles needed for this project.', null=True),
        ),
    ]
