# Generated by Django 5.2 on 2025-05-04 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('collaboration_status', models.CharField(choices=[('OPEN', 'Open to Help'), ('NEEDS', 'Needs Help'), ('NONE', 'Not Looking')], default='NONE', max_length=5, verbose_name='collaboration status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
